language: node_js
node_js:
- '14.16.0'
os:
- linux
sudo: true
env:
  global:
  - ARTIFACTS_PERMISSIONS=public-read
before_install:
- "./scripts/skip_travis_commits.sh"
- sudo add-apt-repository --yes ppa:ubuntu-wine/ppa
- sudo add-apt-repository --yes ppa:arx/release
- sudo apt-get update -d
- sudo apt-get install -y -q innoextract wine python-software-properties
- wine --version
- innoextract --version
- "./scripts/innosetup/innoinstall.sh"
- sudo cp scripts/innosetup/iscc /usr/local/bin/iscc
- iscc /? 2> /dev/null | grep "Inno Setup Preprocessor"
- if [ "${TRAVIS_SECURE_ENV_VARS}" != "false" ]; then openssl aes-256-cbc -K $encrypted_7e3718570525_key
  -iv $encrypted_7e3718570525_iv -in private.json.enc -out src/config/private.json
  -d; fi
before_script:
- git config --global url."https://".insteadOf git://
- npm install
- patch --forward --reject-file=- node_modules/gogs-client/lib/request.js < gogs-client-lib-request.diff
  || ( EXIT_CODE=$?; if [ $EXIT_CODE -gt 1 ]; then exit $EXIT_CODE; fi )
- npm install gulp -g
- npm install bower -g
script: npm test
after_success:
- test $TRAVIS_TEST_RESULT == 0 && $TRAVIS_PULL_REQUEST == "false"
- test -z $TRAVIS_TAG && ./scripts/bump.sh
- wget --no-verbose "https://btt-writer-resources.s3.amazonaws.com/resource_containers.zip"
- if [ -f resource_containers.zip ]; then rm -r ./src/index; fi
- unzip -qq resource_containers.zip -d ./src/index/
- test -f src/index/index.sqlite
- test -d src/index/resource_containers
- bower install
- test -d src/components
- gulp prince
- test -d src/prince
- travis_wait gulp build --win
- travis_wait gulp build --linux
- travis_wait gulp build --osx
- travis_wait gulp release
deploy:
-  provider: s3
   edge: true
   region: us-east-1
   local_dir: release
   upload-dir: ${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}
   glob: 
   acl: public_read
   skip_cleanup: true
   on:
     repo: Bible-Translation-Tools/BTT-Writer-Desktop
     all_branches: true
-  provider: releases
   api_key:
     secure: "EdwxrFkAoTk/B+NdEWmeNWtVAqiu1DcavsWjKZwHn+DfXFx7DjyTk6Ybs5wNP/J/P3BdASe7i5RKoXOlGv52O4UgheWHspmnnbutQtPx6X1izURsciZyum5qJ4l90gJHfQsPPHSJRNsfWO06yQOgEP7Mphbilesh3b0Xa+Hy1SirEDEUoYARlfVN0HP+p3r7RTOCfftDwHSuN1PZvPR6ItPvr+qOjwIoeySZ689YQB7fjdfmQIM1n2tGXa0C8i1F3s9/qud3Gfvfhv1kodd0UGh0uwdN/iBn6JRVVuaNi4Ei6bK8M8g8B3k+LUh19Y7sD87TdVfEX933SApfzyIs6CRlUz9gOwHPEgD4MGoC5dFVgVdL+YAoBrirjrQ2ojt8bUkK+GWlv7rDJaxQNahNwH4D/DWY6JxGgqXN7leE5HKwUpHOnHaS+MGiYnCU+sfuQDpJDQoCbwDPFwM8aqZAwWet9Ya1F7qlvPRz1BRhLx9sOUFAFw1uw9mSy6pkCJHqiQCrTxMb+NKfdm+/VKtN0UiSdkfD63qHItG9+MqXbXelqkqwQ8aM4uneOBM1HDISrU83jzwOFmRB721dd/AHL+8/C3Ftn4J6up1ulaHtd/z2hqQ86NQFllTmOsaMUeQRoCIF2gNt5JOgR0AAMlCkff7DPk+ktUlaNclUYAMAwjk="
   file:
   - "*.exe"
   - "*.zip"
   file_glob: true
   skip_cleanup: true
   overwrite: true
   on:
     tags: true
     repo: Bible-Translation-Tools/BTT-Writer-Desktop
     condition: "-d ./release"
