language: node_js
node_js:
- '6'
os:
- linux
sudo: true
env:
  global:
  - ARTIFACTS_PERMISSIONS=public-read
before_install:
- "./scripts/skip_travis_commits.sh"
- sudo add-apt-repository --yes ppa:ubuntu-wine/ppa
- sudo add-apt-repository --yes ppa:arx/release
- sudo apt-get update -d
- sudo apt-get install -y -q innoextract wine python-software-properties
- wine --version
- innoextract --version
- "./scripts/innosetup/innoinstall.sh"
- sudo cp scripts/innosetup/iscc /usr/local/bin/iscc
- iscc /? 2> /dev/null | grep "Inno Setup Preprocessor"
- if [ "${TRAVIS_SECURE_ENV_VARS}" != "false" ]; then openssl aes-256-cbc -K $encrypted_7e3718570525_key
  -iv $encrypted_7e3718570525_iv -in private.json.enc -out src/config/private.json
  -d; fi
before_script:
- git config --global url."https://".insteadOf git://
- npm install
- patch --forward --reject-file=- node_modules/gogs-client/lib/request.js < gogs-client-lib-request.diff
  || ( EXIT_CODE=$?; if [ $EXIT_CODE -gt 1 ]; then exit $EXIT_CODE; fi )
- npm install gulp -g
- npm install bower -g
script: npm test
after_success:
- test $TRAVIS_TEST_RESULT == 0 && $TRAVIS_PULL_REQUEST == "false"
- test -z $TRAVIS_TAG && ./scripts/bump.sh
- wget --no-verbose "https://btt-writer-resources.s3.amazonaws.com/resource_containers.zip"
- if [ -f resource_containers.zip ]; then rm -r ./src/index; fi
- unzip -qq resource_containers.zip -d ./src/index/
- test -f src/index/index.sqlite
- test -d src/index/resource_containers
- bower install
- test -d src/components
- gulp prince
- test -d src/prince
- gulp build --win
- gulp build --linux
- gulp build --osx
- travis_wait gulp release
addons:
  artifacts:
    s3_region: us-east-1
    working_dir: release
    target_paths:
    - "/${TRAVIS_REPO_SLUG}/${TRAVIS_BRANCH}/${TRAVIS_BUILD_NUMBER}/${TRAVIS_TAG}"
    paths:
    - $(ls release/*.exe | tr "\n" ":")
    - $(ls release/*.zip | tr "\n" ":")
deploy:
  provider: releases
  api_key:
    secure: pcOzsPYBiowoLLb5ZeGOM4RmJq9rYP+ItH0E31UZtJkRyiXRAEoOV6wOdo3JK348SK4q6pDwKuhxB7I0i6Qc5A9tu9qN+SSH/NVjhXVW4yCkBy4Uls6jjEdJYb8Pd4y0ZG7+qvhq5kwOmvU9eavoitSxSGLbXye5EW36xs/PMbtSESquT3G/joqfkyQfC5fX8YoGCZKp97x8wFdrjz6Z2NO6yh4x99TlhFLXm2GpAQJ3SWactYeJWEDx+5m2t4DFqtENyGX3VSCmS9+OPg5u8aj0Wu26TcACtIhJiaD4hBOjSmNDL7ARnlneaAoIpNhVyPqg5R2wPB6qPI1yw22ezIMgqJc3zPPkBmwldzNWCSzq8TRXn0A+lQmiPcKR8xwgGWlza1KB0UAdKcZtWygy/t6Alz0pDi3PSYLi98AyrUpgrXuUkGeRlldkKwT8zPTL/JJN4mLa74/L+vvMN+6Q3kAwyWD21kRU//+2YqiaAl2XhZUyoR2uLMVDisvD6n1+XYEhNEnOWKoFps6HiJq4iFYoVC0sGkqlnaRrPtiisExEG7lhuG8HtJ6KETB7rIsGm/jnE7wbEJg0/aDX2JbEYispLcFzrKeDrJ201zT1mlIzT6eXYj2cCy3X0jOzeNEVz0fA2YxhXL3UsA3ucR7bOMa7HbIYjgTFuS23I1+orzg=
  file:
  - release/*.exe
  - release/*.zip
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: WycliffeAssociates/ts-desktop
    condition: "-d ./release"
