language: node_js

# Turn off caching to avoid any caching problems
cache:
    directories:
    - $HOME/build/unfoldingWord-dev/ts-desktop/node_modules

# Use the Travis Container-Based Infrastructure
sudo: false

before_install:
    - openssl aes-256-cbc -K $encrypted_38675ffc7ca5_key -iv $encrypted_38675ffc7ca5_iv -in config.json.enc -out unit_tests/git/config.json -d

node_js:
  - "5.1"

before_script:
  - npm install
  - npm install gulp -g
script: gulp
