language: node_js

# Turn off caching to avoid any caching problems
cache:
    directories:
    - $HOME/build/unfoldingWord-dev/ts-desktop/node_modules

# Use the Travis Container-Based Infrastructure
sudo: false

node_js:
  - "0.12"
before_script:
  - npm install gulp -g
script: gulp
