name: CI

on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: FranzDiebold/github-env-vars-action@v2.1.0

      - name: Decrypt secret file
        shell: bash
        run: ./.github/scripts/decrypt_secret.sh
        env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}

      # Runs build script
      - name: Buildscript
        shell: bash
        run: ./.github/scripts/build.sh

      #upload builds to AWS nightlybuilds
      - name: set s3 destination_dir for nightly-builds
        run: echo "CURRENT_S3_DESTINATION=$CI_REPOSITORY_OWNER/$CI_REPOSITORY_NAME/$CI_REF_NAME_SLUG/$CI_RUN_NUMBER" >> $GITHUB_ENV
      - name: Upload file to bucket
        uses: shallwefootball/s3-upload-action@v1.1.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: ./release
          destination_dir: ${{ env.CURRENT_S3_DESTINATION }}

      - name: upload artifacts to github releases on tags
        uses: "marvinpinto/action-automatic-releases@v1.2.1"
        if: contains( github.ref, 'refs/tags/v' )
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: release/*.*
